"""COMPLIANT assembler for the Track 3 award review (organizer request, 2026-09-02).

Two constraints imposed by the organizers:
  1. Every *fine-tuned* model in the system must be trained across all TAR task types.
     -> uses ONLY  cosmos_v2  (SFT on `tasks: all`, see training/cosmos_v2/configs/sft.yaml)
        and        cosmos-base (nvidia/Cosmos3-Super, zero-shot, never fine-tuned).
        The task-specialised f1 (7 open-ended tasks) and box-cue (bcq/mcq) checkpoints are NOT used,
        and neither are any artifacts they produced (grounding generations, f1 greedy fallback).
  2. The 1-Yes-1-No structural pair repair must be disabled.
     -> no pair repair, and no cross-task consistency judge, anywhere in this script.

Selection policy is otherwise unchanged: majority voting for the discrete-answer tasks and
MBR-BERTScore medoid for the free-text tasks (the paper's metric-matched selection).

  python inference/assemble_compliant.py --dir inference/full_run \
      --out dataset/official_test/submission_compliant.csv
  python inference/assemble_compliant.py --single-model ...   # strictest reading: cosmos_v2 only

`temporal_localization` is emitted empty: it is not among the nine scored tasks and its only
source in the cached pools was the excluded f1 checkpoint.
"""
import os
import re
import sys
import csv
import json
import argparse
from collections import defaultdict, Counter

import bert_score

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paths import TEST_JSON  # noqa: E402

LET = ["A", "B", "C", "D"]
DESC = ("open_qa", "scene_description", "video_summarization", "causal_linkage",
        "temporal_description")


def parse_answer(s):
    s = s or ""
    m = re.search(r"<answer>(.*?)</answer>", s, re.S)
    if m:
        return m.group(1).strip()
    s = re.sub(r"<think>.*?</think>", "", s, flags=re.S)
    return re.sub(r"^.*?</think>", "", s, flags=re.S).strip()


def extract_yesno(s):
    m = re.search(r"\b(yes|no)\b", (s or "").lower())
    return m.group(1) if m else None


def parse_opts(q):
    m = re.search(r"(?m)^\s*A[.)]\s", q)
    if not m:
        return None
    parts = re.split(r"(?m)^\s*([A-D])[.)]\s+", q[m.start():]); o = {}
    for k in range(1, len(parts) - 1, 2):
        o[parts[k]] = parts[k + 1]
    if set(o) != set(LET):
        return None
    o["D"] = re.split(r"\n\s*\n|\bChoose the correct\b|\bAnswer with\b", o["D"], maxsplit=1)[0]
    return {k: " ".join(v.split()).strip().rstrip("?").strip() for k, v in o.items()}


def norm(s):
    return re.sub(r"[^a-z0-9 ]", "", str(s).lower())[:55]


def stem(q):
    return re.sub(r"[^a-z0-9 ]", "", q.split("\n")[0].strip().lower())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "full_run"))
    ap.add_argument("--out", default="dataset/official_test/submission_compliant.csv")
    ap.add_argument("--single-model", action="store_true",
                    help="strictest reading: use cosmos_v2 only (drop the zero-shot cosmos-base votes)")
    ap.add_argument("--pair-repair", action="store_true",
                    help="OFF by default (the organizers asked for it to be disabled). Enables the "
                         "1-Yes-1-No structural repair on bcq, flipping the lower-margin member of a "
                         "violating pair. Provided so the run that addresses ONLY the model rule can be "
                         "produced from the same script.")
    ap.add_argument("--no-locevent", action="store_true",
                    help="also drop the temporal locevent cue (the only cue derived from another "
                         "task's QUESTION text rather than from the system's own answers)")
    ap.add_argument("--extra-dir", default="",
                    help="dir with the second cosmos_v2 candidate draw (mbr_test_cosmos_s1.json) and the "
                         "additional option-order permutations (extra_perms_cosmos_{base,v2}.json), used to "
                         "restore the candidate-pool size the deployed system had, from compliant models only")
    ap.add_argument("--grounding-dir", default="",
                    help="dir with task-matched grounding pools REGENERATED BY cosmos_v2 "
                         "(locevent/summ_fullevent/summco/evidence). Grounding is per-task prompting "
                         "inside the one system; the cues here are produced by the compliant model.")
    a = ap.parse_args()
    D = a.dir

    def J(name, default=None):
        p = os.path.join(D, name)
        return json.load(open(p)) if os.path.exists(p) else (default if default is not None else {})

    items = json.load(open(TEST_JSON))["items"]
    cv2 = J("cosmos_v2_votetta.json")        # cosmos_v2: bcq/bcq_oe samples, mcq/mcq_oe picks
    cv2desc = J("mbr_test_cosmos.json")      # cosmos_v2: free-text candidate pool
    o_cv2 = J("orphan_votes_cosmos_v2.json", {})
    if a.single_model:
        cz, o_cz = {}, {}
    else:
        cz = J("cosmos_votetta.json")        # cosmos-base (zero-shot)
        o_cz = J("orphan_votes_cosmos.json", {})

    # cross-format pairing (closed <-> open-ended sibling of the same question)
    byv = defaultdict(lambda: defaultdict(list))
    for it in items:
        byv[it["video_id"]][it["task_type"]].append(it)
    mcq_pair, bcq_pair = {}, {}
    for v, d in byv.items():
        for x in d.get("mcq", []):
            ox = parse_opts(x["question"])
            for y in d.get("mcq_openended", []):
                oy = parse_opts(y["question"])
                if ox and oy and stem(x["question"]) == stem(y["question"]) and \
                        len(set(map(norm, ox.values())) & set(map(norm, oy.values()))) >= 3:
                    mcq_pair[str(x["item_index"])] = str(y["item_index"])
                    mcq_pair[str(y["item_index"])] = str(x["item_index"]); break
        for x in d.get("bcq", []):
            for y in d.get("bcq_openended", []):
                if stem(re.split(r"Answer with|Provide|Choose", x["question"])[0]) == \
                        stem(re.split(r"Answer with|Provide|Choose", y["question"])[0]):
                    bcq_pair[str(x["item_index"])] = str(y["item_index"])
                    bcq_pair[str(y["item_index"])] = str(x["item_index"]); break

    scorer = bert_score.BERTScorer(lang="en", rescale_with_baseline=True)

    def mbr(cands, cap=48):
        # dedup (order-preserving) + cap, matching the deployed selector in inference/common.py:
        # without dedup a duplicated candidate scores 1.0 against its own copy and wins unfairly.
        cands = list(dict.fromkeys([c for c in cands if c]))[:cap]
        if len(cands) < 2:
            return cands[0] if cands else ""
        n = len(cands); pc, pr = [], []
        for i in range(n):
            for j in range(n):
                if i != j:
                    pc.append(cands[i]); pr.append(cands[j])
        _, _, f = scorer.score(pc, pr); f = [float(x) for x in f]
        k = 0; u = [0.0] * n
        for i in range(n):
            for j in range(n):
                if i != j:
                    u[i] += f[k]; k += 1
        return cands[max(range(n), key=lambda i: u[i])]

    def cv2_stances(iid):
        """cosmos_v2's own free-text Yes/No stances for a bcq_oe item."""
        return [x for x in (extract_yesno(parse_answer(s))
                            for s in (cv2.get(iid, {}).get("samples") or [])) if x]

    # ---- optional grounding pools (regenerated by cosmos_v2) ----
    G = a.grounding_dir
    def GJ(name):
        p = os.path.join(G, name)
        return json.load(open(p)) if G and os.path.exists(p) else {}
    locev, summfe, summco, ev = (GJ("locevent_temporal_test.json"), GJ("summ_fullevent_test.json"),
                                 GJ("summco_test.json"), GJ("evidence_test.json"))
    if a.no_locevent:
        locev = {}

    X = a.extra_dir
    def XJ(name):
        q = os.path.join(X, name)
        return json.load(open(q)) if X and os.path.exists(q) else {}
    desc_s1 = XJ("mbr_test_cosmos_s1.json")
    xperm_cb, xperm_cv2 = XJ("extra_perms_cosmos_base.json"), XJ("extra_perms_cosmos_v2.json")
    if a.single_model:
        xperm_cb = {}

    def xpicks(i):
        return list((xperm_cb.get(i, {}) or {}).get("picks") or []) + \
               list((xperm_cv2.get(i, {}) or {}).get("picks") or [])

    def gsamp(store, i):
        return [x for x in (parse_answer(s) for s in (store.get(i, {}).get("samples") or [])) if x]

    def ev_for(i, task):
        e = ev.get(i, {})
        return gsamp(ev, i) if e.get("task") == task else []

    pred, empty, bcq_votes = {}, Counter(), {}
    for it in items:
        i = str(it["item_index"]); t = it["task_type"]; p = ""

        if t == "bcq":
            # cross-format vote, restricted to compliant models: cosmos-base direct +
            # cosmos_v2 direct + cosmos_v2's own open-ended stance on the sibling question.
            st = list(cz.get(i, {}).get("votes", []))            # cosmos-base direct votes
            st += list(cv2.get(i, {}).get("votes", []))          # cosmos_v2 direct votes
            st += cv2_stances(bcq_pair[i]) if i in bcq_pair else \
                [x for x in (o_cv2.get(i, {}).get("votes") or []) if x]
            st = [x for x in st if x]
            bcq_votes[i] = st
            if st:
                p = "Yes" if Counter(st).most_common(1)[0][0] == "yes" else "No"

        elif t == "mcq":
            o = parse_opts(it["question"])
            pool = list(cz.get(i, {}).get("picks", [])) + list(cv2.get(i, {}).get("picks", [])) + xpicks(i)
            if i in mcq_pair:
                pool += list(cv2.get(mcq_pair[i], {}).get("picks") or []) + xpicks(mcq_pair[i])
            else:
                pool += list(o_cv2.get(i, {}).get("picks") or [])
            pool = [x for x in pool if o and x in set(map(norm, o.values()))]
            if pool and o:
                la = next((k for k, vv in o.items() if norm(vv) == Counter(pool).most_common(1)[0][0]), None)
                if la:
                    p = la

        elif t == "mcq_openended":
            ob = parse_opts(it["question"])
            pool = list(cz.get(i, {}).get("picks", [])) + list(cv2.get(i, {}).get("picks") or []) + xpicks(i)
            if i in mcq_pair:                                    # sibling closed-format picks
                pool += list(cv2.get(mcq_pair[i], {}).get("picks") or []) + xpicks(mcq_pair[i])
            pool = [x for x in pool if ob and x in set(map(norm, ob.values()))]
            if pool and ob:
                lb = next((k for k, vv in ob.items() if norm(vv) == Counter(pool).most_common(1)[0][0]), None)
                if lb:
                    p = f"{lb}. {ob[lb]}"

        elif t == "bcq_openended":
            allp = [x for x in (parse_answer(s) for s in (cv2.get(i, {}).get("samples") or [])) if x]
            if allp:
                votes = cv2_stances(i)
                if i in bcq_pair:
                    votes += [x for x in cz.get(bcq_pair[i], {}).get("votes", []) if x]
                else:
                    votes += [x for x in (o_cz.get(i, {}).get("votes") or []) if x]
                vst = Counter(votes).most_common(1)[0][0] if votes else "no"
                cand = [x for x in allp if extract_yesno(x) == vst] or allp
                p = mbr(cand)

        elif t in DESC:
            r0 = [x for x in (parse_answer(s) for s in (cv2desc.get(i, {}).get("samples") or [])) if x]
            r1 = [x for x in (parse_answer(s) for s in (desc_s1.get(i, {}).get("samples") or [])) if x]
            rich = [x for pair in zip(r0, r1) for x in pair] + r0[len(r1):] + r1[len(r0):]
            if t == "open_qa":
                pool = ev_for(i, "open_qa") + rich
            elif t == "causal_linkage":
                pool = ev_for(i, "causal_linkage") + rich
            elif t == "video_summarization":
                pool = gsamp(summco, i) + gsamp(summfe, i) + rich
            elif t == "temporal_description":
                pool = gsamp(locev, i)                 # pure locevent, as in the deployed recipe
                if len(pool) < 2:
                    pool = rich
            else:                                      # scene_description: ungrounded by design
                pool = rich
            if pool:
                p = mbr(pool)

        # temporal_localization: unscored, only source was the excluded f1 checkpoint -> left empty

        pred[i] = p

    # ---- optional 1-Yes-1-No structural repair (disabled by default) ----
    if a.pair_repair:
        def margin_of(i):
            v = bcq_votes.get(i) or []
            return max(Counter(v).values()) / len(v) if v else 0.0
        flipped = 0
        for vid, d in byv.items():
            b = d.get("bcq", [])
            if len(b) != 2:
                continue
            i1, i2 = str(b[0]["item_index"]), str(b[1]["item_index"])
            if pred.get(i1, "").strip().lower() != pred.get(i2, "").strip().lower():
                continue                                  # already one-Yes-one-No
            flip = i1 if margin_of(i1) <= margin_of(i2) else i2
            pred[flip] = "No" if pred[flip].strip().lower() == "yes" else "Yes"
            flipped += 1
        print(f"[pair-repair] flipped {flipped} violating pairs")

    # ---- bcq_openended: regenerate No-items from evidence, aligned to the final bcq stance ----
    if ev:
        for it in items:
            i = str(it["item_index"])
            if it["task_type"] != "bcq_openended" or i not in bcq_pair:
                continue
            if pred.get(bcq_pair[i], "").strip().lower() != "no":   # final bcq decision
                continue
            cand = ev_for(i, "bcq_oe_no")
            if cand:
                m = mbr(cand)
                if extract_yesno(m) == "no":
                    pred[i] = m

    rows = []
    for it in items:
        i = str(it["item_index"]); p = pred.get(i, "")
        if not p.strip():
            empty[it["task_type"]] += 1
        rows.append({"item_index": i, "prediction": p})

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["item_index", "prediction"])
        w.writeheader(); w.writerows(rows)
    mode = "cosmos_v2 only" if a.single_model else "cosmos_v2 + zero-shot cosmos-base"
    print(f"[compliant:{mode}] wrote {a.out}: {len(rows)} rows, empty per task {dict(empty)}")


if __name__ == "__main__":
    main()
